
import java.awt.Desktop;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.util.Random;
import java.util.Scanner;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JScrollPane;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author user
 */
public class Quiz_Frame extends javax.swing.JFrame {

    Scanner scan = new Scanner(System.in);

    private Image image1;
    private int RandomUserNumber;
    private int length = 3;
    private String UserNameSuffix;
    
    
    
    public Quiz_Frame() {
        initComponents();

        Random rand = new Random();
        
        UserNameSuffix = "@quiz.edu.com";
        
            //parametres for entered data
        String username2 = JTextField_RegisterName.getText();
        String Remail = JTextField_RegisterEmail.getText();
        String RPassword1 = JPasswordField_Register1.getText();
        String RPassword2 = JPasswordField_Register2.getText();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanel_OnlineQuiz = new javax.swing.JPanel();
        JLabel_OnlineQuiz = new javax.swing.JLabel();
        JPanel_Login = new javax.swing.JPanel();
        JLabel_Register = new javax.swing.JLabel();
        JLabel_RegisterName = new javax.swing.JLabel();
        JLabel_RegisterEmail = new javax.swing.JLabel();
        JLabel_RegisterPassword = new javax.swing.JLabel();
        JCheckbox_RegisterAgree = new javax.swing.JCheckBox();
        JButton_RegisterButton = new javax.swing.JButton();
        JTextField_RegisterName = new javax.swing.JTextField();
        JTextField_RegisterEmail = new javax.swing.JTextField();
        JPasswordField_Register1 = new javax.swing.JPasswordField();
        JPasswordField_Register2 = new javax.swing.JPasswordField();
        JLabel_RegisterPassword2 = new javax.swing.JLabel();
        JCheckBox_RegisterVisible = new javax.swing.JCheckBox();
        JPanel_Register = new javax.swing.JPanel();
        JLabel_Login = new javax.swing.JLabel();
        JLabel_LoginName = new javax.swing.JLabel();
        JLabel_LoginPassword = new javax.swing.JLabel();
        JCheckbox_LoginRememberMe = new javax.swing.JCheckBox();
        JButton_LoginButton = new javax.swing.JButton();
        JPasswordField_LoginPassword = new javax.swing.JPasswordField();
        JTextField_LoginUsername = new javax.swing.JTextField();
        JCheckBox_LoginVisible = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JPanel_OnlineQuiz.setBackground(new java.awt.Color(255, 204, 204));

        JLabel_OnlineQuiz.setFont(new java.awt.Font("Times New Roman", 1, 70)); // NOI18N
        JLabel_OnlineQuiz.setText("          O N L I N E  Q U I Z");
        JLabel_OnlineQuiz.setAlignmentX(30.0F);
        JLabel_OnlineQuiz.setAlignmentY(30.0F);
        JLabel_OnlineQuiz.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout JPanel_OnlineQuizLayout = new javax.swing.GroupLayout(JPanel_OnlineQuiz);
        JPanel_OnlineQuiz.setLayout(JPanel_OnlineQuizLayout);
        JPanel_OnlineQuizLayout.setHorizontalGroup(
            JPanel_OnlineQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel_OnlineQuizLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(JLabel_OnlineQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 1003, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPanel_OnlineQuizLayout.setVerticalGroup(
            JPanel_OnlineQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel_OnlineQuizLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(JLabel_OnlineQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        JPanel_Login.setBackground(new java.awt.Color(255, 204, 204));

        JLabel_Register.setFont(new java.awt.Font("Times New Roman", 1, 70)); // NOI18N
        JLabel_Register.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel_Register.setText("Register");

        JLabel_RegisterName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JLabel_RegisterName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel_RegisterName.setText("Name");

        JLabel_RegisterEmail.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JLabel_RegisterEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel_RegisterEmail.setText("Email");

        JLabel_RegisterPassword.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JLabel_RegisterPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel_RegisterPassword.setText("Password");

        JCheckbox_RegisterAgree.setBackground(new java.awt.Color(255, 255, 255));
        JCheckbox_RegisterAgree.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        JCheckbox_RegisterAgree.setText("I agree privacy policy");
        JCheckbox_RegisterAgree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCheckbox_RegisterAgreeActionPerformed(evt);
            }
        });

        JButton_RegisterButton.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        JButton_RegisterButton.setText("SIGN IN");
        JButton_RegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_RegisterButtonActionPerformed(evt);
            }
        });

        JTextField_RegisterName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        JTextField_RegisterName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextField_RegisterNameActionPerformed(evt);
            }
        });

        JTextField_RegisterEmail.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        JTextField_RegisterEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextField_RegisterEmailActionPerformed(evt);
            }
        });

        JPasswordField_Register1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        JPasswordField_Register1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPasswordField_Register1ActionPerformed(evt);
            }
        });

        JPasswordField_Register2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        JPasswordField_Register2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPasswordField_Register2ActionPerformed(evt);
            }
        });

        JLabel_RegisterPassword2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JLabel_RegisterPassword2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel_RegisterPassword2.setText("Password again");

        JCheckBox_RegisterVisible.setText("See Password");
        JCheckBox_RegisterVisible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCheckBox_RegisterVisibleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanel_LoginLayout = new javax.swing.GroupLayout(JPanel_Login);
        JPanel_Login.setLayout(JPanel_LoginLayout);
        JPanel_LoginLayout.setHorizontalGroup(
            JPanel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanel_LoginLayout.createSequentialGroup()
                .addGroup(JPanel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(JPanel_LoginLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(JCheckbox_RegisterAgree, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JButton_RegisterButton)
                        .addGap(127, 127, 127))
                    .addGroup(JPanel_LoginLayout.createSequentialGroup()
                        .addGap(0, 114, Short.MAX_VALUE)
                        .addComponent(JLabel_Register, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JPanel_LoginLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(JPanel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JPanel_LoginLayout.createSequentialGroup()
                                .addGroup(JPanel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(JPanel_LoginLayout.createSequentialGroup()
                                        .addGroup(JPanel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(JLabel_RegisterEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(JLabel_RegisterName, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(48, 48, 48)
                                        .addGroup(JPanel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(JTextField_RegisterEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(JTextField_RegisterName, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(JPanel_LoginLayout.createSequentialGroup()
                                        .addComponent(JLabel_RegisterPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(JPasswordField_Register2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(JPanel_LoginLayout.createSequentialGroup()
                                .addComponent(JLabel_RegisterPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(JPasswordField_Register1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JCheckBox_RegisterVisible, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(21, 21, 21))
        );
        JPanel_LoginLayout.setVerticalGroup(
            JPanel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel_LoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLabel_Register)
                .addGap(18, 18, 18)
                .addGroup(JPanel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTextField_RegisterName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLabel_RegisterName))
                .addGap(18, 18, 18)
                .addGroup(JPanel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabel_RegisterEmail)
                    .addComponent(JTextField_RegisterEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(JPanel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabel_RegisterPassword)
                    .addComponent(JPasswordField_Register1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JCheckBox_RegisterVisible))
                .addGap(30, 30, 30)
                .addGroup(JPanel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabel_RegisterPassword2)
                    .addComponent(JPasswordField_Register2))
                .addGap(25, 25, 25)
                .addGroup(JPanel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JButton_RegisterButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JCheckbox_RegisterAgree, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JPanel_Register.setBackground(new java.awt.Color(255, 204, 204));

        JLabel_Login.setFont(new java.awt.Font("Times New Roman", 1, 70)); // NOI18N
        JLabel_Login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel_Login.setText("Log in");

        JLabel_LoginName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JLabel_LoginName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel_LoginName.setText("Username");

        JLabel_LoginPassword.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JLabel_LoginPassword.setText("Password");

        JCheckbox_LoginRememberMe.setBackground(new java.awt.Color(255, 255, 255));
        JCheckbox_LoginRememberMe.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        JCheckbox_LoginRememberMe.setText("Remember Me");
        JCheckbox_LoginRememberMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCheckbox_LoginRememberMeActionPerformed(evt);
            }
        });

        JButton_LoginButton.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        JButton_LoginButton.setText("LOG IN");
        JButton_LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_LoginButtonActionPerformed(evt);
            }
        });

        JPasswordField_LoginPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JPasswordField_LoginPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPasswordField_LoginPasswordActionPerformed(evt);
            }
        });

        JTextField_LoginUsername.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JTextField_LoginUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextField_LoginUsernameActionPerformed(evt);
            }
        });

        JCheckBox_LoginVisible.setText("See Password");
        JCheckBox_LoginVisible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCheckBox_LoginVisibleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanel_RegisterLayout = new javax.swing.GroupLayout(JPanel_Register);
        JPanel_Register.setLayout(JPanel_RegisterLayout);
        JPanel_RegisterLayout.setHorizontalGroup(
            JPanel_RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel_RegisterLayout.createSequentialGroup()
                .addGroup(JPanel_RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanel_RegisterLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(JLabel_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPanel_RegisterLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(JCheckbox_LoginRememberMe, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPanel_RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(JCheckBox_LoginVisible, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(JPanel_RegisterLayout.createSequentialGroup()
                            .addGroup(JPanel_RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(JPanel_RegisterLayout.createSequentialGroup()
                                    .addGap(37, 37, 37)
                                    .addComponent(JLabel_LoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(JPanel_RegisterLayout.createSequentialGroup()
                                    .addGap(29, 29, 29)
                                    .addComponent(JLabel_LoginName, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(18, 18, 18)
                            .addGroup(JPanel_RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(JPasswordField_LoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JTextField_LoginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanel_RegisterLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(JButton_LoginButton)
                .addGap(53, 53, 53))
        );
        JPanel_RegisterLayout.setVerticalGroup(
            JPanel_RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel_RegisterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLabel_Login)
                .addGap(43, 43, 43)
                .addGroup(JPanel_RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLabel_LoginName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTextField_LoginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(JPanel_RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLabel_LoginPassword)
                    .addComponent(JPasswordField_LoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(JCheckBox_LoginVisible)
                .addGap(10, 10, 10)
                .addComponent(JCheckbox_LoginRememberMe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(3, 3, 3)
                .addComponent(JButton_LoginButton)
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JPanel_OnlineQuiz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(JPanel_Login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JPanel_Register, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPanel_OnlineQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JPanel_Login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JPanel_Register, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JCheckbox_RegisterAgreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCheckbox_RegisterAgreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCheckbox_RegisterAgreeActionPerformed

    private void JPasswordField_Register2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPasswordField_Register2ActionPerformed


    }//GEN-LAST:event_JPasswordField_Register2ActionPerformed

    private void JPasswordField_Register1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPasswordField_Register1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPasswordField_Register1ActionPerformed

    private void JTextField_RegisterNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextField_RegisterNameActionPerformed


    }//GEN-LAST:event_JTextField_RegisterNameActionPerformed

    private void JTextField_RegisterEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextField_RegisterEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextField_RegisterEmailActionPerformed

    private void JCheckbox_LoginRememberMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCheckbox_LoginRememberMeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCheckbox_LoginRememberMeActionPerformed

    private void JPasswordField_LoginPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPasswordField_LoginPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPasswordField_LoginPasswordActionPerformed

    private void JTextField_LoginUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextField_LoginUsernameActionPerformed

        // JTextField JTextField_LoginUsername  = new JTextField();
        JTextField_LoginUsername.setFocusTraversalKeysEnabled(true);
        JTextField_LoginUsername.setFocusTraversalKeysEnabled(true);
        JTextField_LoginUsername.setFocusable(true);
        JTextField_LoginUsername.setRequestFocusEnabled(true);
    }//GEN-LAST:event_JTextField_LoginUsernameActionPerformed

    private void JButton_LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_LoginButtonActionPerformed
        String username2 = JTextField_RegisterName.getText();
        String Remail = JTextField_RegisterEmail.getText();
        String RPassword1 = JPasswordField_Register1.getText();
        String RPassword2 = JPasswordField_Register2.getText();
        

        if (JTextField_LoginUsername.getText().equals(username2) && JPasswordField_LoginPassword.getText().equals(RPassword1)) {
        try {
             Desktop.getDesktop().browse(new URL("https://quizlet.com").toURI());
         } 
        catch (Exception e) {}
            JOptionPane.showMessageDialog(null, "Success!");
            
        } else {
            
            JOptionPane.showMessageDialog(null, "Username or Password is not correct!");

        }
     
    }//GEN-LAST:event_JButton_LoginButtonActionPerformed

    private void JButton_RegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_RegisterButtonActionPerformed
            
            //parametres for entered data
        String username2 = JTextField_RegisterName.getText();
        String Remail = JTextField_RegisterEmail.getText();
        String RPassword1 = JPasswordField_Register1.getText();
        String RPassword2 = JPasswordField_Register2.getText();
        
            // contidion if name is empty
        if (JTextField_RegisterName.getText().equals("")
                && JTextField_RegisterEmail.getText().equals(Remail)
                && JPasswordField_Register1.getText().equals(RPassword1)
                && JPasswordField_Register2.getText().equals(RPassword2)
                && JCheckbox_RegisterAgree.isSelected()) {

            JOptionPane.showMessageDialog(null, "Please make sure filled all fields!");

        } 
        //contidion if email is empty
        else if (JTextField_RegisterName.getText().equals(username2)
                && JTextField_RegisterEmail.getText().equals("")
                && JPasswordField_Register1.getText().equals(RPassword1)
                && JPasswordField_Register2.getText().equals(RPassword2)
                && JCheckbox_RegisterAgree.isSelected()) {

            JOptionPane.showMessageDialog(null, "Please make sure filled all fields!");

        } 
        //contidion if first password field is empty
        else if (JTextField_RegisterName.getText().equals(username2)
                && JTextField_RegisterEmail.getText().equals(Remail)
                && JPasswordField_Register1.getText().equals("")
                && JPasswordField_Register2.getText().equals(RPassword2)
                && JCheckbox_RegisterAgree.isSelected()) {

            JOptionPane.showMessageDialog(null, "Please make sure filled all fields!");

        } 
        //contidion if second password field is empty
        else if (JTextField_RegisterName.getText().equals(username2)
                && JTextField_RegisterEmail.getText().equals(Remail)
                && JPasswordField_Register1.getText().equals(RPassword1)
                && JPasswordField_Register2.getText().equals("")
                && JCheckbox_RegisterAgree.isSelected()) {

            JOptionPane.showMessageDialog(null, "Please make sure filled all fields!");
            
            
        } 
        //contidion if all fields are empty
        else if (JTextField_RegisterName.getText().equals("")
                && JTextField_RegisterEmail.getText().equals("")
                && JPasswordField_Register1.getText().equals("")
                && JPasswordField_Register2.getText().equals("")
                && !JCheckbox_RegisterAgree.isSelected()) {

            JOptionPane.showMessageDialog(null, "Make sure entered you information correct");

        } 
        //condition, if all fields are filled except CHECK BOX
        else if (JTextField_RegisterName.getText().equals(username2)
                && JTextField_RegisterEmail.getText().equals(Remail)
                && JPasswordField_Register1.getText().equals(RPassword1)
                && JPasswordField_Register2.getText().equals(RPassword2)
                && !JCheckbox_RegisterAgree.isSelected()) {

            JOptionPane.showMessageDialog(null, "Please be sure you select Privacy policy");

        } 
        //condition, if all fields are filled
        else if (JTextField_RegisterName.getText().equals(username2)
                && JTextField_RegisterEmail.getText().equals(Remail)
                && JPasswordField_Register1.getText().equals(RPassword1)
                && JPasswordField_Register2.getText().equals(RPassword2)
                && JCheckbox_RegisterAgree.isSelected()) {
            
            JTextField info = new JTextField();
            info.setText("Your login name is: "+JTextField_RegisterName.getText().toLowerCase()+"_"+randomUserName(length)+UserNameSuffix);
            
            JOptionPane.showMessageDialog(null, "You have registered!");
            //JOptionPane.showMessageDialog(null, "Your login name is: "+JTextField_RegisterName.getText().toLowerCase()+"_"+randomUserName(length)+UserNameSuffix);
            JOptionPane.showMessageDialog(null, new JScrollPane(info), "RESULT", JOptionPane.INFORMATION_MESSAGE);

        } else {

            JOptionPane.showMessageDialog(null, "Make sure entered you information correct");
        }
    }//GEN-LAST:event_JButton_RegisterButtonActionPerformed

    private void JCheckBox_RegisterVisibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCheckBox_RegisterVisibleActionPerformed

    if(JCheckBox_RegisterVisible.isSelected()){
    JPasswordField_Register1.setEchoChar((char)0);
    JPasswordField_Register2.setEchoChar((char)0);
    
            
            
            }
    else{
    JPasswordField_Register1.setEchoChar('*');
    JPasswordField_Register2.setEchoChar('*');
}
    }//GEN-LAST:event_JCheckBox_RegisterVisibleActionPerformed

    private void JCheckBox_LoginVisibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCheckBox_LoginVisibleActionPerformed
    
        if(JCheckBox_LoginVisible.isSelected()){
        JPasswordField_LoginPassword.setEchoChar((char)0);
        
    
            
            
            }
        else{
        JPasswordField_LoginPassword.setEchoChar('*');
      
}
    }//GEN-LAST:event_JCheckBox_LoginVisibleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quiz_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quiz_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quiz_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quiz_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Quiz_Frame().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButton_LoginButton;
    private javax.swing.JButton JButton_RegisterButton;
    private javax.swing.JCheckBox JCheckBox_LoginVisible;
    private javax.swing.JCheckBox JCheckBox_RegisterVisible;
    private javax.swing.JCheckBox JCheckbox_LoginRememberMe;
    private javax.swing.JCheckBox JCheckbox_RegisterAgree;
    private javax.swing.JLabel JLabel_Login;
    private javax.swing.JLabel JLabel_LoginName;
    private javax.swing.JLabel JLabel_LoginPassword;
    private javax.swing.JLabel JLabel_OnlineQuiz;
    private javax.swing.JLabel JLabel_Register;
    private javax.swing.JLabel JLabel_RegisterEmail;
    private javax.swing.JLabel JLabel_RegisterName;
    private javax.swing.JLabel JLabel_RegisterPassword;
    private javax.swing.JLabel JLabel_RegisterPassword2;
    private javax.swing.JPanel JPanel_Login;
    private javax.swing.JPanel JPanel_OnlineQuiz;
    private javax.swing.JPanel JPanel_Register;
    private javax.swing.JPasswordField JPasswordField_LoginPassword;
    private javax.swing.JPasswordField JPasswordField_Register1;
    private javax.swing.JPasswordField JPasswordField_Register2;
    private javax.swing.JTextField JTextField_LoginUsername;
    private javax.swing.JTextField JTextField_RegisterEmail;
    private javax.swing.JTextField JTextField_RegisterName;
    // End of variables declaration//GEN-END:variables

    

   private String randomUserName(int length){
    String NumberSet = "1234567890";
    char[] number = new char[length];
     for(int i = 0; i<length; i++){
        int rand = (int)(Math.random()* NumberSet.length());
        number[i]= NumberSet.charAt(rand);
     }
     return new String (number);

}
}
